### ISSUE TITLE
Opening anime?

### ISSUE THREAD

**Issue by Romangelo** [HaiKonofanDesu/konofan-assets-jp-sortet#2]
Are they included in this project? If they're there, which folder they're in?

Thanks.

**Comment by HaiKonofanDesu** [comment]
Hey there, sorry for the late response.

The Opening Files are not yet in there, but we found a hopefully easy way to get them. Just need to find the time to manually extract them and put them together.

Not sure if I will put them here or in a separate Repo or even just on YouTube with a hidden Playlist. Once they are here I'll let you know

**Comment by Romangelo** [comment]
Thanks.

**Comment by HaiKonofanDesu** [comment]
https://github.com/HaiKonofanDesu/konofan-videos

Sorry for the Delay, it's hard getting specially oder files but here is the first commit
