### ISSUE TITLE
Wonder where are those character picture from main story ?

### ISSUE THREAD

**Issue by sdugoten** [HaiKonofanDesu/konofan-assets-jp-sortet#4]
Like some of these from main story

https://i.imgur.com/j4wPIud.jpeg

**Comment by HaiKonofanDesu** [comment]
https://github.com/HaiKonofanDesu/konofan-assets-jp-sortet/tree/main/Assets/AddressableAssetsStore/UnityAssets/Story/Prefab/Sprite/Still

Should all be in there. There are also Event Storys included hence why you find welfare artwoks in there as well
