### ISSUE TITLE
Discord Link Dead

### ISSUE THREAD

**Issue by 2x35** [HaiKonofanDesu/konofan-assets-jp-sortet#5]
As title suggests, either your vanity link was lost because of not enough boosts or some other reason. But at the moment it does not work.

**Comment by HaiKonofanDesu** [comment]
Ye the boost ran out, did not think of that. Should be updated now, thanks for the info!

**Comment by JudgeDreddpool** [comment]
Just a smol update, but the Discord link is broken again.

**Comment by HaiKonofanDesu** [comment]
> Just a smol update, but the Discord link is broken again.

Oh thanks for the Info, will fix it tomorrow!
